services:
  api:
    build: ./packages/api
    container_name: solerosso-api
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./packages/api/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build: ./packages/web
    container_name: solerosso-web
    restart: always
    ports:
      - "3000:3000"
